
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
    <script>
      // try catch 测试代码块 
 
          //   try 尝试去执行
          //   catch 是捕获错误，并抛出
          //   throw 在try块中定义错误信息
      /*
        1.try catch  是成对出现的
        2.catch(err) 中的err就是try中定义的错误信息
       */
      function myFunction(){
          try{
              var x=document.getElementById("demo").value;
              if(x=="")    throw "empty";
              if(isNaN(x)) throw "not a number";
              if(x>10)     throw "too high";
              if(x<5)      throw "too low";

          }catch(err){
              var y=document.getElementById("mess");
              y.innerHTML="Error: " + err + ".";
          }
      }
    </script>

<h1>My First JavaScript</h1>
<p>Please input a number between 5 and 10:</p>
<input id="demo" type="text">
<button type="button" onclick="myFunction()">Test Input</button>
<p id="mess"></p>
</body>
</html>